spring:
  profiles:
    active: default
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: none # sql 자동 실행 시 none 처
    properties:
      hibernate:
        format_sql: true
  redis:
    master:
      host: localhost
      port: 6379
    slaves:
      - host: localhost
        port: 6380

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: DEBUG

---
# 개발 프로파일 (dev) 설정
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG  # 개발 환경에서는 DEBUG 로그 레벨로 설정

server:
  port: 8080

---
# 프로덕션 프로파일 (prd) 설정
spring:
  config:
    activate:
      on-profile: prd

logging:
  level:
    root: INFO  # 프로덕션 환경에서는 INFO 로그 레벨로 설정

server:
  port: 8080
